# Generated by Django 5.2.1 on 2025-05-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goldenqa', '0003_alter_question_tag_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goldenqa.question'),
        ),
    ]
